---
- name: Verificar espacio en disco
  hosts: all
  become: yes
  tasks:
    - name: Mostrar espacio disponible en /
      command: df -h /
      register: root_space

    - name: Mostrar resultado de espacio en /
      debug:
        var: root_space.stdout_lines

    - name: Mostrar espacio disponible en /mnt/c
      command: df -h /mnt/c
      register: c_space
      ignore_errors: yes   # en caso de que no exista /mnt/c

    - name: Mostrar resultado de espacio en /mnt/c
      debug:
        var: c_space.stdout_lines
