---
- name: Verificar espacio en disco
  hosts: all
  become: yes
  tasks:
    - name: Mostrar espacio disponible en /
      command: df -h /
      register: root_space

    - name: Mostrar resultado de espacio en /
      debug:
        var: root_space.stdout_lines

    